CUDA_VISIBLE_DEVICES=0 python3 src/train.py \
    --domain_name cartpole \
    --task_name swingup \
    --action_repeat 8 \
    --mode train \
    --train_steps 500000 \
    --use_rot \
    --num_shared_layers 8 \
    --seed 0 \
    --work_dir logs/cartpole_swingup/rot/0 \
    --save_model
