name: pad
channels:
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip
  - pip:
    - gym==0.23.0
    - pillow==6.2.0
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - scikit-image
    - seaborn
    - tensorboard
    - tqdm

